"""make utilizador_id nullable

Revision ID: 03b1671293b3
Revises: b9c8d7e6f5a4
Create Date: 2026-09-07 22:12:01.759828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03b1671293b3'
down_revision: Union[str, Sequence[str], None] = 'b9c8d7e6f5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contador', 'utilizador_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key('fk_recarga_pagamento_id', 'recarga', 'pagamento', ['pagamento_id'], ['id'], use_alter=True)
    op.drop_constraint(op.f('utilizadores_telefone_key'), 'utilizadores', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('utilizadores_telefone_key'), 'utilizadores', ['telefone'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('fk_recarga_pagamento_id', 'recarga', type_='foreignkey')
    op.alter_column('contador', 'utilizador_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
