"""dual_meters

Revision ID: 32dffb9f9c5f
Revises: 03b1671293b3
Create Date: 2026-09-07 23:35:54.589353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32dffb9f9c5f'
down_revision: Union[str, Sequence[str], None] = '03b1671293b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contador', sa.Column('canal', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_contador_dispositivo_id'), 'contador', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_contador_dispositivo_id'), 'contador', ['dispositivo_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('contador', 'canal')
    # ### end Alembic commands ###
