"""schema_inicial_der

Revision ID: 4b724b2ae0f8
Revises: 
Create Date: 2026-09-02 20:31:45.529865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b724b2ae0f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispositivo_iot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mac_address', sa.String(), nullable=False),
    sa.Column('firmware_version', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('ultimo_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dispositivo_iot'))
    )
    op.create_index(op.f('ix_dispositivo_iot_mac_address'), 'dispositivo_iot', ['mac_address'], unique=True)
    op.create_table('utilizadores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telefone', sa.String(length=9), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('papel', sa.String(), nullable=False),
    sa.Column('biometria_activa', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['auth.users.id'], name=op.f('fk_utilizadores_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_utilizadores'))
    )
    op.create_index(op.f('ix_utilizadores_telefone'), 'utilizadores', ['telefone'], unique=True)
    op.create_table('contador',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('numero_serie', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('latitude', sa.Double(), nullable=True),
    sa.Column('longitude', sa.Double(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('kwh_saldo', sa.Double(), nullable=False),
    sa.Column('estado_rele', sa.Boolean(), nullable=False),
    sa.Column('ultima_sincronizacao', sa.DateTime(), nullable=True),
    sa.Column('ultima_recarga', sa.DateTime(), nullable=True),
    sa.Column('utilizador_id', sa.UUID(), nullable=False),
    sa.Column('dispositivo_id', sa.Uuid(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivo_iot.id'], name=op.f('fk_contador_dispositivo_id_dispositivo_iot')),
    sa.ForeignKeyConstraint(['utilizador_id'], ['utilizadores.id'], name=op.f('fk_contador_utilizador_id_utilizadores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contador')),
    sa.UniqueConstraint('dispositivo_id', name=op.f('uq_contador_dispositivo_id'))
    )
    op.create_index(op.f('ix_contador_numero_serie'), 'contador', ['numero_serie'], unique=True)
    op.create_table('alerta',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('mensagem', sa.String(), nullable=False),
    sa.Column('utilizador_id', sa.UUID(), nullable=False),
    sa.Column('contador_id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contador_id'], ['contador.id'], name=op.f('fk_alerta_contador_id_contador')),
    sa.ForeignKeyConstraint(['utilizador_id'], ['utilizadores.id'], name=op.f('fk_alerta_utilizador_id_utilizadores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerta'))
    )
    op.create_table('recarga',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('montante_pago', sa.Double(), nullable=False),
    sa.Column('moeda', sa.String(), nullable=False),
    sa.Column('kwh_creditado', sa.Double(), nullable=True),
    sa.Column('metodo', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('token_sts', sa.String(), nullable=True),
    sa.Column('token_sts_usado', sa.Boolean(), nullable=False),
    sa.Column('is_primeira_compra_mes', sa.Boolean(), nullable=False),
    sa.Column('recarregado_em', sa.DateTime(), nullable=True),
    sa.Column('contador_id', sa.Uuid(), nullable=False),
    sa.Column('utilizador_id', sa.UUID(), nullable=False),
    sa.Column('pagamento_id', sa.Uuid(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contador_id'], ['contador.id'], name=op.f('fk_recarga_contador_id_contador')),
    sa.ForeignKeyConstraint(['pagamento_id'], ['pagamento.id'], name='fk_recarga_pagamento_id', use_alter=True),
    sa.ForeignKeyConstraint(['utilizador_id'], ['utilizadores.id'], name=op.f('fk_recarga_utilizador_id_utilizadores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recarga'))
    )
    op.create_index(op.f('ix_recarga_token_sts'), 'recarga', ['token_sts'], unique=True)
    op.create_table('comando_iot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('hmac_token', sa.String(), nullable=False),
    sa.Column('enviado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('dispositivo_id', sa.Uuid(), nullable=False),
    sa.Column('recarga_id', sa.Uuid(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivo_iot.id'], name=op.f('fk_comando_iot_dispositivo_id_dispositivo_iot')),
    sa.ForeignKeyConstraint(['recarga_id'], ['recarga.id'], name=op.f('fk_comando_iot_recarga_id_recarga')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comando_iot'))
    )
    op.create_table('desdobramento_recarga',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('montante_total', sa.Double(), nullable=False),
    sa.Column('val_energia', sa.Double(), nullable=False),
    sa.Column('iva', sa.Double(), nullable=False),
    sa.Column('divida_paga', sa.Double(), nullable=False),
    sa.Column('tx_radio', sa.Double(), nullable=False),
    sa.Column('tx_lixo', sa.Double(), nullable=False),
    sa.Column('kwh_calculado', sa.Double(), nullable=False),
    sa.Column('recarga_id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recarga_id'], ['recarga.id'], name=op.f('fk_desdobramento_recarga_recarga_id_recarga')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_desdobramento_recarga')),
    sa.UniqueConstraint('recarga_id', name=op.f('uq_desdobramento_recarga_recarga_id'))
    )
    op.create_table('pagamento',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('referencia_mpesa', sa.String(), nullable=True),
    sa.Column('montante', sa.Double(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('recarga_id', sa.Uuid(), nullable=False),
    sa.Column('utilizador_id', sa.UUID(), nullable=False),
    sa.Column('actualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recarga_id'], ['recarga.id'], name=op.f('fk_pagamento_recarga_id_recarga')),
    sa.ForeignKeyConstraint(['utilizador_id'], ['utilizadores.id'], name=op.f('fk_pagamento_utilizador_id_utilizadores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pagamento'))
    )
    op.create_index(op.f('ix_pagamento_referencia_mpesa'), 'pagamento', ['referencia_mpesa'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagamento_referencia_mpesa'), table_name='pagamento')
    op.drop_table('pagamento')
    op.drop_table('desdobramento_recarga')
    op.drop_table('comando_iot')
    op.drop_index(op.f('ix_recarga_token_sts'), table_name='recarga')
    op.drop_table('recarga')
    op.drop_table('alerta')
    op.drop_index(op.f('ix_contador_numero_serie'), table_name='contador')
    op.drop_table('contador')
    op.drop_index(op.f('ix_utilizadores_telefone'), table_name='utilizadores')
    op.drop_table('utilizadores')
    op.drop_index(op.f('ix_dispositivo_iot_mac_address'), table_name='dispositivo_iot')
    op.drop_table('dispositivo_iot')
    # ### end Alembic commands ###
