"""Add is_primary to contador

Revision ID: bc3c235b0400
Revises: 8ed656a70d3c
Create Date: 2026-09-09 17:37:35.520426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc3c235b0400'
down_revision: Union[str, Sequence[str], None] = '8ed656a70d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contador', sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_constraint(op.f('uq_contador_dispositivo_canal'), 'contador', type_='unique')
    op.drop_constraint(op.f('desdobramento_recarga_recarga_id_fkey'), 'desdobramento_recarga', type_='foreignkey')
    op.create_foreign_key(op.f('fk_desdobramento_recarga_recarga_id_recarga'), 'desdobramento_recarga', 'recarga', ['recarga_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_desdobramento_recarga_recarga_id_recarga'), 'desdobramento_recarga', type_='foreignkey')
    op.create_foreign_key(op.f('desdobramento_recarga_recarga_id_fkey'), 'desdobramento_recarga', 'recarga', ['recarga_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_contador_dispositivo_canal'), 'contador', ['dispositivo_id', 'canal'], postgresql_nulls_not_distinct=False)
    op.drop_column('contador', 'is_primary')
    # ### end Alembic commands ###
