"""Add divida_pendente to Contador

Revision ID: f32dd6091188
Revises: bc3c235b0400
Create Date: 2026-09-10 00:41:39.896491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f32dd6091188'
down_revision: Union[str, Sequence[str], None] = 'bc3c235b0400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contador', sa.Column('divida_pendente', sa.Double(), nullable=False, server_default="0.0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contador', 'divida_pendente')
    # ### end Alembic commands ###
